config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :venues do
    resources :offers, only: [:new, :create, :index]
  end

  resources :offers, only: [:show, :destroy] do
    resources :bids, only: [:new, :create]
  end
  get "/offers", to: "offers#index_all"
  
  resources :brands do
    resources :bids, only: [:index, :show]
  end

  resources :bids, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :brand

  validates :offer_amount, presence: true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :user
  has_many :bids

  validates :brand_name, presence: true
  validates :description, presence: true
  validates :address, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :venue
  has_many :bids

  CATEGORIES = ["Gin", "Whiskey", "Whisky", "Vodka", "Rum", "Lager", "Bitter", "Cider", "Tonic Water", "Energy Drink"]

  validates :min_bid, presence: true
  validates :contract_length, presence: true
  validates :estimated_volume, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :brand
  has_one :venue
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :offers

  validates :venue_name, presence: true
  validates :address, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
    @bids = Bid.all
  end

  def show
    @bid = Bid.find(params[:id])
  end

  def new
    @offer = Offer.find(params[:offer_id])
    @bid = Bid.new
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @bid = Bid.new(bid_params.merge(offer_id: params[:offer_id], brand_id: current_user.brand.id))
    if @bid.save!
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def destroy
    @bid.delete(@bid)
  end

  private

  def bid_params
    params.require(:bid).permit(:offer_amount, :additional)
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params.merge(user_id: current_user.id))
    if @brand.save
      redirect_to brand_path(@brand)
    else
      render :new 
    end   
  end

  def index
    @brand = Brand.all
  end

  def show
    @brand = Brand.find(params[:id])
  end


  def edit
  end

  def update
    if @brand.update(brand_params)
      redirect_to brand_path(@brand)
    else
      render :edit
    end  
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.delete
  end

  private

  def brand_params
    params.require(:brand).permit(:brand_name, :address, :phone_number, :description)  
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :show_limited, :edit, :destroy]

  def index
    @offers = Offer.where(venue_id: current_user.venue.id)
  end

  def index_all
    if params[:category].present?
      @dropdown_text = params[:category]
      @offers = Offer.where(category: params[:category]).order(:created_at)
    else
      @dropdown_text = "Select Category"
      @offers = Offer.all.order(:created_at)
    end
  end

  def show
    @brand = current_user.brand
    @bid = Bid.new
    @bids = @offer.bids.order(:offer_amount).reverse_order
  end

  def new
    @venue = Venue.find(params[:venue_id])
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params.merge(venue_id: params[:venue_id]))
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
  end

  def destroy
    @offer.destroy
    redirect_to root_path
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:min_bid, :contract_length, :estimated_volume, :category, :venue_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @bids = Bid.last(9)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :destroy]

  def index
    @venues = Venue.all
  end

  def show
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params.merge(user_id: current_user.id))
    if @venue.save!
      redirect_to @venue
    else
      render :new
    end
  end

  def edit
  end

  def update
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  def destroy
    @venue.destroy
    redirect_to root_path
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
  end

  def venue_params
    params.require(:venue).permit(:venue_name, :address, :phone_number, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bids/_form.html.erb
<div class="bid-form-card">
  <%= simple_form_for [@offer, @bid] do |f| %>
    <div class="form-inputs">
      <%= f.label :offer_amount, label: 'Bid amount (in whole pounds)' %>
      <%= f.input :offer_amount, placeholder: '500', label: false %>
      <%= f.input :additional, placeholder: '100 branded glasses and 20 branded T-shirts' %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, { class: "btn btn-primary", value: "Create Bid" } %>
    </div>
  <% end %>
</div>

app/views/bids/index.html.erb
<div class="bid-background">
  <div class="bid-container">
    <div class="bid-cards text-center">
      <h1>Current Bids</h1>
    <div class="not-a-grid">
    <% @bids.each do |bid| %>
     <div class="card-product">
      <img class="card-image" src="https://upload.wikimedia.org/wikipedia/en/9/9b/Camden_Town_Brewery_logo.png" />
      <div class="card-product-infos">
        <p><strong><%= (Offer.find(bid.offer_id)).venue.venue_name %></strong></p>
        <p>Bid: £<%= bid.offer_amount %></p>
        <p>Extras: <%= bid.additional %></p>
         <span id="text-muted">Created <%= time_ago_in_words(bid.updated_at) %> ago</span>
      </div>
    </div>
     <% end %>
    </div>
  </div>
  </div>
</div>

app/views/bids/new.html.erb
<div class="container">
  <h1>New Bid</h1>
  
  <%= render 'form' %>
</div>

app/views/bids/show.html.erb
<h1>Bids#show</h1>
<p>Find me in app/views/bids/show.html.erb</p>

app/views/brands/_form.html.erb
<%= simple_form_for @brand do |f| %>
  <div class="form-inputs">
    <%= f.input :brand_name, placeholder: 'EzTenda Gin' %>
    <%= f.input :address, placeholder: '123, Street Road, London EZ7 3ND' %>
    <%= f.input :phone_number, placeholder: '01234567890' %>
    <%= f.input :description, as: :text, placeholder: 'Please write a short description about your brand' %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, { class: "btn btn-primary", value: "Create Brand" } %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Brands#edit</h1>
<p>Find me in app/views/brands/edit.html.erb</p>

app/views/brands/index.html.erb
<h1>Brands#index</h1>
<p>Find me in app/views/brands/index.html.erb</p>
<%= link_to 'back', root_path, class: "button" %>

app/views/brands/new.html.erb
<div class="container">
  <h1>New Brand</h1>
  
  <%= render 'form' %>
</div>

app/views/brands/show.html.erb
<h1>Brands#show</h1>
<p>Find me in app/views/brands/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EztendaPrototype</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="d-flex flex-column min-vh-100">
    <%= yield %>
    <%= render "shared/navbar" %>
    <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= simple_form_for [@venue, @offer] do |f| %>
  <div class="form-inputs">
    <%= f.input :min_bid, label: 'Minimum bid (in whole pounds)', placeholder: '500' %>
    <%= f.input :contract_length, label: 'Contract length (in months)', placeholder: '12 months' %>
    <%= f.input :estimated_volume, label: 'Estimated volume of sales', placeholder: '1000 bottles' %>
    <%= f.input :category, collection: Offer::CATEGORIES, selected: "Gin" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, { class: "btn btn-primary", value: "Create Offer" } %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Offers#edit</h1>
<p>Find me in app/views/offers/edit.html.erb</p>

app/views/offers/index.html.erb
<div class="venue-offers">
<br>

<div class="container my-5 fs-container">
  <div class="request-cards text-center">
  <h1>My Offers</h1>
    <div class="container">
    <% @offers.each do |offer| %>
    <div class="card-product">
    <img class="card-image" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos card-offer">
        <h4><strong><%= offer.venue.venue_name %></strong></h4> 
            <ul>
              <li>Category: <%= offer.category %></li>
              <li>Minimun Bid:  <%= offer.min_bid %> </li>
              <li>Contract Length:  <%= offer.contract_length %></li>
              <li>Estimated Volume:  <%= offer.estimated_volume %></li>
            </ul>
            <span id="text-muted">Created <%= time_ago_in_words(offer.updated_at) %> ago</span>
        </div>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/offers/index_all.html.erb
<div class="venue-offers">
  <div class="fs-container">
    <div class="index-container">
      <h1 class="index-title">CURRENT OFFERS</h1>
      <div class="dropdown-and-clear-button">
        <div class="dropdown" id="category-dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= @dropdown_text %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <% Offer::CATEGORIES.each do |category| %>
              <a class="dropdown-item category-item" href="/offers.php?category=<%= category %>"><%= category %></a>
            <% end %>
          </div>
        </div>
        <%= link_to "Clear filter", offers_path %>
      </div>

      <div class="offers-list">
        <% @offers.each do |offer| %>
          <div class="card-product all-offers-card">
            <img class="card-image" src="https://upload.wikimedia.org/wikipedia/en/9/9b/Camden_Town_Brewery_logo.png" />
            <div class="card-product-infos">
              <p id="offer-card-title"><strong><%= offer.venue.venue_name %> - <%= offer.category %></strong></p>
              <div class="min-bid-est-vol">
                <p id="min-bid">Minimum Bid: £<%= offer.min_bid %></p>
                <p id="est-vol">Estimated Volume: <%= offer.estimated_volume %></p>
              </div>
              <p><%= offer.bids.count %> Bids</p>
              <span id="text-muted">Created <%= time_ago_in_words(offer.updated_at) %> ago</span>
            </div>
            <%= link_to "Make a bid", offer_path(offer), class: "btn bid-button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container form-container">
  <h1>New Offer</h1>

  <%= render 'form' %>
</div>

app/views/offers/show.html.erb
<div class="venue-offers">
  <div class="fs-container">
    <div class="offer-show-container">
      <div class="offers-bids-list">

        <h1>Offer</h1>
        <div class="card-product show-offer-card" id="show-offer-card">
          <img class="card-image" src="https://upload.wikimedia.org/wikipedia/en/9/9b/Camden_Town_Brewery_logo.png" />
          <div class="card-product-infos">
            <p id="offer-card-title"><strong><%= @offer.venue.venue_name %> - <%= @offer.category %></strong></p>
            <div class="min-bid-est-vol">
              <p id="min-bid">Minimum Bid: £<%= @offer.min_bid %></p>
              <p id="est-vol">Estimated Volume: <%= @offer.estimated_volume %></p>
            </div>
            <p><%= @offer.bids.count %> Bids</p>
            <span id="text-muted">Created <%= time_ago_in_words(@offer.updated_at) %> ago</span>
          </div>
        </div>

        <h2>Current Bids</h2>

        <% @bids.each do |bid| %>
          <div class="card-product show-bid-card">
            <img class="card-image" src="https://upload.wikimedia.org/wikipedia/en/9/9b/Camden_Town_Brewery_logo.png" />
            <div class="card-product-infos">
              <p id="offer-card-title"><strong><%= bid.brand.brand_name %></strong></p>
              <p>Bid: <strong>£<%= bid.offer_amount %></strong></p>
              <p>Extras: <%= bid.additional %></p>
            </div>
          </div>
        <% end %>

      </div>

      <%= render partial: 'bids/form' %>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hero-image">
  <div class="hero-text">
    <div class="opaque-background">
      <div class="page-title"><h1>A great deal better</h1></div>
      <div id="slideshow">
        <div>
          <h3>A better way for bars and brand to do business</h3>
        </div>
        <div>
          <h3>An online auction where bars can tender their listings and brand can bid for them</h3>
        </div>
        <div>
          <h3>Empowering bars and brands</h3>
        </div>
      </div>
      <div class="index-buttons">
      <div class="brand-buttons">
        <a class="brand-btn"><%= link_to 'Brands', brands_path, class: "button" %></a>
      </div>
      <div class="venue-button">
        <a class="venues_btn"><%= link_to 'Venues', venues_path, class: "button" %></a>
      </div>
      <div class="brand-buttons">
      <%= link_to "View All Offers", offers_path, class: "button" %>
      </div>
      </div>
      <% if user_signed_in? && !current_user.brand.nil? %>
      <%= link_to 'Current Bids', brand_bids_path(current_user.brand), class: "button" %>
      <% end %>
    </div>
  </div>
</div>



<!-- <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div> -->

app/views/shared/_card.html.erb
<div class="card-product">
  <img class="card-image" src="https://upload.wikimedia.org/wikipedia/en/9/9b/Camden_Town_Brewery_logo.png" />
  <div class="card-product-infos">
    <h2>Product name</h2>
    <p>Product description with <strong>relevant info</strong> only.</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer"style="
    background-color: black;
    height: 100px;">
  <a class="navbar-brand"><p>ez</p><p id="tenda">tenda</p></a>
  <div class="footer-links" style="text-align: center;">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-transparent d-flex justify-content-around">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><p>ez</p><p id="tenda">tenda</p></a>
    <form class="d-flex">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    <div class="navbar-right">
      <% if user_signed_in? %>
        <%= link_to "Create offer", new_venue_offer_path(current_user.venue), class: "btn new-offer" %>
      <% else %>
        <a class="btn new-offer" href="/users/sign_in">Create offer</a>
      <% end %>
      <li class="nav-item dropdown">
        <i class="fas fa-bars dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <% if current_user.brand %>
              <%= link_to "My bids", brand_bids_path(current_user.brand), class: "dropdown-item" %>
            <% end %>
            <% if current_user.venue %>
              <%= link_to "My offers", venue_offers_path(current_user.venue), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <a class="dropdown-item" href="/users/sign_in">Log in</a>
            <a class="dropdown-item" href="/users/sign_up">Sign up</a>
          <% end %>
        </div>
      </li>
    </div>
  </div>
</nav>

app/views/shared/bidcard.html.erb
<div class="not-a-grid">
    <% @bids.each do |bid| %>
     <div class="card-product">
      <img class="card-image" src="https://upload.wikimedia.org/wikipedia/en/9/9b/Camden_Town_Brewery_logo.png" />
      <div class="card-product-infos">
        <p> <%= bid.brand.brand_name %> </p>
         <%= bid.offer_amount %>
         <%= bid.additional %>
         <span id="text-muted">Created <%= time_ago_in_words(bid.updated_at) %> ago</span>
      </div>
    </div>
     <% end %>
    </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/venues/_form.html.erb
<%= simple_form_for @venue do |f| %>
  <div class="form-inputs">
    <%= f.input :venue_name, placeholder: 'The EzTenda Arms' %>
    <%= f.input :address, placeholder: '123, Street Road, London EZ7 3ND' %>
    <%= f.input :phone_number, placeholder: '01234567890' %>
    <%= f.input :description, as: :text, placeholder: 'Please write a short description about your establishment' %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, { class: "btn btn-primary", value: "Create Venue" } %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Venues#edit</h1>
<p>Find me in app/views/venues/edit.html.erb</p>

app/views/venues/index.html.erb
<h1>Venues#index</h1>
<p>Find me in app/views/venues/index.html.erb</p>
 <%= link_to 'back', root_path, class: "button" %>

app/views/venues/new.html.erb
<div class="container">
  <h1>New Venue</h1>
  
  <%= render 'form' %>
</div>

app/views/venues/show.html.erb
<h1>Venues#show</h1>
<p>Find me in app/views/venues/show.html.erb</p>